version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - ireturn
    - maintidx
    - mnd
    - nestif
    - nonamedreturns
    - testpackage
    - varnamelen
  settings:
    funlen:
      lines: 65
    gocritic:
      enabled-tags:
        - performance
        - opinionated
        - diagnostic
        - style
    govet:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - funlen
        path: ._test\.go
      - linters:
          - gocritic
        path: path.go
        text: appendAssign
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
