# .goreleaser.yml
version: 2
project_name: inmfortune

before:
  hooks:
    - go mod download

builds:
  - id: inmfortune-bin
    dir: .
    main: ./cmd/inmfortune
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X main.GitTag={{.Tag}}
      - -X main.GitHash={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: inmfortune
    formats: ['tar.gz']
    ids: [inmfortune-bin]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']

nfpms:
  - id: packages
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/s0rg/inm
    description: Impaled Northern Moonforest song title generator for cli
    maintainer: s0rg
    license: MIT
    vendor: s0rg
    formats:
      - deb
      - rpm

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'
