# ci workflow
name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
          check-latest: true
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
